/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prog.h"

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_String (XDR *xdrs, String *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->String_val, (u_int *) &objp->String_len, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
